name: Auto Update Plugins Base

on:
  schedule:
    # Запуск каждые 6 часов
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Позволяет запускать бота вручную кнопкой "Run workflow"

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 curl_cffi requests

      - name: Run parser script
        run: python update_base.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add synths.json effects.json all_search.json
          # Проверяем изменения, чтобы скрипт не падал, если база не обновилась
          git diff --quiet && git diff --staged --quiet || (git commit -m "Авто-обновление базы плагинов [skip ci]" && git push)
